// rosetta-stone/vue-vite/src/App.vue
<template>
  <div ref="containerRef" class="viz-container"></div>
</template>

<script setup>
import { ref, onMounted, reactive, watch } from 'vue';
import { main } from './viz'; // Imports the D3 visualization logic

const containerRef = ref(null);
// Use reactive for the state object to make it deeply reactive.
// This state will be passed to the D3 visualization.
const vueState = reactive({});

// Wrapper for setState that will be passed to the D3 visualization.
// This function updates the reactive `vueState` object.
const setStateWrapper = (updaterFn) => {
  const newState = updaterFn(vueState); // Calculate the new state based on the current

  // Update properties of the reactive vueState object to match newState
  // First, remove keys from vueState that are not in newState
  for (const key in vueState) {
    if (!(key in newState)) {
      delete vueState[key];
    }
  }
  // Then, add/update keys from newState to vueState
  for (const key in newState) {
    vueState[key] = newState[key];
  }
  // The `watch` below will detect these changes and call `main` again.
};

onMounted(() => {
  // Initial call to render the D3 visualization when the component mounts
  // and the container div (containerRef.value) is available.
  if (containerRef.value) {
    main(containerRef.value, {
      state: vueState,
      setState: setStateWrapper,
    });
  }
});

// Watch for changes in `vueState` and re-render the D3 visualization.
// `deep: true` ensures that changes to nested properties of `vueState` are also detected.
watch(
  vueState,
  () => {
    if (containerRef.value) {
      main(containerRef.value, {
        state: vueState,
        setState: setStateWrapper,
      });
    }
  },
  { deep: true },
);
</script>

<style scoped>
/* Scoped styles for App.vue */
.viz-container {
  height: 100vh;
  width: 100vw; /* Ensure it takes full width */
  display: block; /* Ensure it behaves as a block element */
}
</style>

// rosetta-stone/svelte-vite/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { main } from './viz'; // Imports the D3 visualization logic
  let containerElement;
  let svelteState = {}; // This will hold the state for the visualization

  // Wrapper for setState that will be passed to the D3 visualization
  // This ensures that when the D3 code calls setState, Svelte's reactivity is triggered.
  const setStateWrapper = (updaterFn) => {
    svelteState = updaterFn(svelteState);
    // The reactive block below ( $: ) will automatically call `main` again due to `svelteState` changing.
  };

  // This is a reactive statement. It re-runs whenever `svelteState` or `containerElement` changes.
  // It ensures the D3 visualization is updated when the state changes.
  $: if (containerElement && typeof main === 'function') {
    main(containerElement, { state: svelteState, setState: setStateWrapper });
  }

  onMount(() => {
    // Initial call to render the D3 visualization when the component mounts
    // and the container div is available.
    if (containerElement) {
      main(containerElement, { state: svelteState, setState: setStateWrapper });
    }
  });
</script>

<div bind:this={containerElement} class="viz-container"></div>

<style>
  .viz-container {
    height: 100vh;
    width: 100vw; /* Ensure it takes full width */
    display: block; /* Ensure it behaves as a block element */
  }
</style>
